#include<stdio.h>
#include<stdlib.h>
#include<string.h>

FILE *fp1,*fp2,*fp3;

void listing()
{
	int i,j,k,l,m,flag,flag1,temp,flags=0,flagn=0;
	char str[50],str1[50],str2[50],str3[50],str4[50],str5[10],t[10];
	fp1=fopen("intermediate.txt","r");
	fp2=fopen("oc.txt","w+");
	
	while(!feof(fp1))
	{
		flag=0;
		fscanf(fp1,"%s",str);
		if(strcmp(str,"START")==0)
		{
			flagn=1;
			fprintf(fp2,"\t%s\t",str);
			fscanf(fp1,"%s",str);
			fprintf(fp2,"%s\n",str);
		}
		/*else if(((str[0]!='0')&&(str[0]!='1'))&&(flagn!=0))
		{
			fprintf(fp2,"\t%s\t",str);
			fscanf(fp1,"%s",str);
			fprintf(fp2,"%s\t",str);
			fscanf(fp1,"%s",str);
			fprintf(fp2,"%s\n",str);
		}*/
		else if(strcmp(str,"END")==0)
		{
			fprintf(fp2,"\t%s\t",str);
			fscanf(fp1,"%s",str);
			fprintf(fp2,"%s\n",str);
			break;
		}
		else
		{
			fprintf(fp2,"%s\t",str);
			fscanf(fp1,"%s",str);
			fprintf(fp2,"%s\t",str);
			fp3=fopen("optab.txt","r");
			while(!feof(fp3))
			{
				fscanf(fp3,"%s",str1);
				if(strcmp(str,str1)==0)
				{
					flag=1;
					fscanf(fp3,"%s",str2);
					break;
				}
			}
			fclose(fp3);
			if(flag!=0)
			{
				fscanf(fp1,"%s",str);
				fprintf(fp2,"%s\t",str);
				fp3=fopen("symtab.txt","r");
				while(!feof(fp3))
				{
					fscanf(fp3,"%s",str3);
					if(strcmp(str,str3)==0)
					{
						flags=1;
						fscanf(fp3,"%s",str4);
						break;
					}
				}
				fclose(fp3);
				if(flags!=0)
				{
					fprintf(fp2,"%s%s\n",str2,str4);
				}
				else
				{
					fprintf(fp2,"%s0000\n",str2);
				}
				flags=0;
			}
			else
			{
				fscanf(fp1,"%s",str);
				fprintf(fp2,"%s\t",str);
                        	fp3=fopen("optab.txt","r");
                        	while(!feof(fp3))
                        	{
                                	fscanf(fp3,"%s",str1);
                                	if(strcmp(str,str1)==0)
                                	{
                                        	flag=1;
                                        	fscanf(fp3,"%s",str2);
                                        	break;
                                	}
                        	}
                        	fclose(fp3);
                        	if(flag!=0)
                        	{
                                	fscanf(fp1,"%s",str);
                                	fprintf(fp2,"%s\t",str);
                                	fp3=fopen("symtab.txt","r");
                                	while(!feof(fp3))
                                	{
                                        	fscanf(fp3,"%s",str3);
                                        	if(strcmp(str,str3)==0)
                                        	{
							flags=1;
                                                	fscanf(fp3,"%s",str4);
                                                	break;
                                        	}
                                	}
                                	fclose(fp3);
					if(flags!=0)
					{
                                		fprintf(fp2,"%s%s\n",str2,str4);
					}
					else
					{
						fprintf(fp2,"%s0000\n",str2);
					}
					flags=0;

				}
				else if((strcmp(str,"WORD")==0)||(strcmp(str,"BYTE")==0))
				{
					if(strcmp(str,"WORD")==0)
					{
						fscanf(fp1,"%s",str);
						fprintf(fp2,"%s\t",str);
						temp=atoi(str);
						if(temp>15)
						{
							fprintf(fp2,"0000%X\n",temp);
						}
						else
						{
							fprintf(fp2,"00000%X\n",temp);
						}	
					}
					else
					{
						fscanf(fp1,"%s",str);
						fprintf(fp2,"%s\t",str);
						k=2;
						if(str[0]=='C')
						{
							while(str[k]!='`')
							{
								fprintf(fp2,"%X",str[k++]);
							}
						}
						else
						{
							while(str[k]!='`')
							{
								fprintf(fp2,"%c",str[k++]);
							}
						}
						fprintf(fp2,"\n");
					}
				}
				else
				{
					fscanf(fp1,"%s",str);
					fprintf(fp2,"%s\n",str);
				}
			}						
		}
	}
	fclose(fp1);
	fclose(fp2);
}

void objectprogram()
{
	int i,j,k,c,flag=0,flag1=0,flag2,t,flags=0,te,flagm=0;
	char str[50],str5[50],str1[50],str2[50],str3[50],str4[50],temp[10],lngth[10];
	fp1=fopen("oc.txt","r");
	fp2=fopen("obpgm.txt","w+");
	fp3=fopen("Length.txt","r");
	fprintf(fp2,"H^");
	fscanf(fp1,"%s",str);
	if(strcmp(str,"START")==0)
	{
		flag1=1;
		fscanf(fp1,"%s",str);
		fprintf(fp2,"%s^",str);
		fscanf(fp1,"%s",str);
	}
	/*else if((flagm==0)&&((str[0]!='0')&&(str[0]!='1')))
	{
			flagm=1;
			flag1=1;
			fprintf(fp2,"%s^",str);
			fscanf(fp1,"%s",str);
			fscanf(fp1,"%s",str);
			fprintf(fp2,"%s",str);
			fscanf(fp1,"%s",str);
	}*/
	else
	{
		fprintf(fp2,"%s^",str);
	}
	fscanf(fp3,"%s",str1);
	fprintf(fp2,"%s\n",str1);
	fclose(fp3);
	fprintf(fp2,"T^");
	fprintf(fp2,"%s^",str);
	i=0;
	while((i*3)<=30)
	{
		i++;
		strcpy(str1,str);
		fscanf(fp1,"%s",str);
		fscanf(fp1,"%s",str);
		if((strcmp(str,"RESW")==0)||(strcmp(str,"RESB")==0)/*||(strcmp(str,"WORD")==0)||(strcmp(str,"BYTE")==0)*/)
		{
			break;
		}
		else
		{
			strcpy(str2,str1);
			fscanf(fp1,"%s",str);
			fscanf(fp1,"%s",str);
		}
	}
	i=i-1;
	fclose(fp1);
	printf("%d\n%s\n",i,str2);
	fp1=fopen("oc.txt","r");
	/*if((flag1!=0)&&(flagm!=0))
	{
		fscanf(fp1,"%s",str);
		fscanf(fp1,"%s",str);
		fscanf(fp1,"%s",str);
	}*/
	if(flag1!=0)
	{
		fscanf(fp1,"%s",str);
		fscanf(fp1,"%s",str);
	}
	if((i*3)>15)
	{
		fprintf(fp2,"%X^",(i*3));
	}
	else
	{
		fprintf(fp2,"0%X^",(i*3));
	}
	fscanf(fp1,"%s",str);
	while(strcmp(str,str2)!=0)
	{
		for(j=0;j<2;j++)
		{
			fscanf(fp1,"%s",str);
		}
		if(strcmp(str,"RESW")==0||strcmp(str,"RESB")==0)
		{
			fprintf(fp2,"\n");
			break;
		}
		if(strcmp(str,"WORD")==0||strcmp(str,"BYTE")==0)
		{
			fscanf(fp1,"%s",str);
		}
		fscanf(fp1,"%s",str);
		fprintf(fp2,"%s^",str);
		fscanf(fp1,"%s",str);
	}
	
	fscanf(fp1,"%s",str);
	printf("%s\n",str);
	//fprintf(fp2,"%s\n",str);
	i=0;c=0;
	while(!feof(fp1))
	{
			fscanf(fp1,"%s",str);
			b1:
			if(strcmp(str,"END")==0)
			{
				break;
			}
			strcpy(str3,str);
			for(j=0;j<2;j++)
			{
				fscanf(fp1,"%s",str);
			}
			if((strcmp(str,"RESW")==0)||(strcmp(str,"RESB")==0))
			{
				if(c==0)
				{
					for(j=0;j<2;j++)
					{
						fscanf(fp1,"%s",str);
					}
					if(strcmp(str,"END")==0)
						break;
					else
						goto b1;
				}
				else
				{
					flags=1;
					goto c1;
				}	
			}		
			else
			{
				if(c==0)
				{
					strcpy(str5,str3);
				}
				strcpy(str4,str3);
				c++;
				if(strcmp(str,"BYTE")==0)
					i++;
				else
					i=i+3;
				fscanf(fp1,"%s",str);
				fscanf(fp1,"%s",str);
				fscanf(fp1,"%s",str);
				if(strcmp(str,"END")==0)
					flags=1;
				else
					goto b1;
			}
			
			c1:
			if(flags!=0)
			{
				printf("%s\n%s\n",str5,str4);
				fprintf(fp2,"T^");
				fprintf(fp2,"%s^",str5);
				if(i>15)
				{
					fprintf(fp2,"%X^",i);
				}
				else
				{
					fprintf(fp2,"0%X^",i);
				}
				fclose(fp1);
				fp1=fopen("oc.txt","r");
				fscanf(fp1,"%s",str);
				while(strcmp(str,str5)!=0)
				{
					fscanf(fp1,"%s",str);
				}
				while(strcmp(str,str4)!=0)
				{
					for(j=0;j<4;j++)
					{
						fscanf(fp1,"%s",str);
					}
					fprintf(fp2,"%s^",str);
					fscanf(fp1,"%s",str);
				}
				for(j=0;j<4;j++)
					fscanf(fp1,"%s",str);
				printf("%s\n",str);
				fprintf(fp2,"%s\n",str);
				c=0;
				flags=0;
				i=0;
			}
	}
	fprintf(fp2,"E\n");
	fclose(fp1);
	fclose(fp2);
}	

main()
{
	listing();
	objectprogram();
}
	
