#include<stdio.h>
#include<string.h>
#include<math.h>
#include<stdlib.h>

char tbl[50][50];
int tb=0,tb1=0;


void cl()
{
	FILE *fp,*fp1,*fp2,*fp3;
	int noe=0,tbaa,temtem,stol1,stol2,noet=0,th=0,noc=0,counter=0,noc1=0,tem,m1=0,tem1,tem2,tem3,flag=0,flag1=0,start1,start=0,st=0,i=0,j=0,k=0,l=0;
	char temm[10],critic[6],str[50],str1[50],temp[50],sign[10],rest[10],modi1[50][50],modi2[50][50],stad[10][10];
	//printf("\nHELLO\n");
	fp=fopen("objpgm.txt","r");
	fp1=fopen("estab.txt","r");
	fp2=fopen("result.txt","w");
	//fp3=fopen("test.txt","w");
	//printf("\nhi1\n");
	//fprintf(fp3,"hello\n");
	while(!feof(fp))
	{
		fscanf(fp,"%s",str);
		if(strcmp(str,"E")==0)
			noe++;
	}
	fclose(fp);
	noe--;
	fp1=fopen("estab.txt","r");
	while(!feof(fp1))
	{
		fscanf(fp1,"%s",str1);
		if(strcmp(str1,"--")==0)
		{
			fscanf(fp1,"%s",str);
			strcpy(stad[st++],str);
		}
	}
	fclose(fp1);
	fp=fopen("objpgm.txt","r");

	//printf("\nReaches\n");	
	while(!feof(fp))
	{
		//start=atoi(stad[l++]);
		b1:
		j=0;
		if(flag1!=1)
		{
			start=strtol(stad[l++],NULL,16);
			start1=start;
		}
		else
		{
			//printf("\n%X\n",start1);
			//start1=start1+16;
			start=start1;
			start1=start1+16;
			//fprintf(fp2,"\n");
		}
		fscanf(fp,"%s",str);
		fscanf(fp,"%s",str);
		strcpy(rest,str);
		while(strcmp(str,"E")!=0)
		{
			if(strcmp(str,"M")==0)
			{
				//printf("\nM\n");
				//if(flag1!=0)
					//printf("\nSecond M\n");
				fscanf(fp,"%s",str);
				strcpy(modi1[m1],str);
				if(flag1==1)
					printf("%s\n",modi1[m1]);
				fscanf(fp,"%s",str);
				fscanf(fp,"%s",str);
				sign[m1]=str[0];
				for(i=1;i<strlen(str);i++)
					temp[j++]=str[i];
				temp[j]='\0';
				j=0;
				fp1=fopen("estab.txt","r");
				while(strcmp(str1,temp)!=0)
					fscanf(fp1,"%s",str1);
				fscanf(fp1,"%s",str1);
				strcpy(modi2[m1++],str1);
				/*if(flag1==1)
					printf("%s\n",modi2[m1-1]);*/
				//if(flag1!=0)
				//	printf("\nSecond M got \n");
			}
			fscanf(fp,"%s",str);
		}
		fclose(fp1);
		fclose(fp);
		fp=fopen("objpgm.txt","r");
		while(strcmp(str,rest)!=0)
			fscanf(fp,"%s",str);
		while(strcmp(str,"T")!=0)
			fscanf(fp,"%s",str);
		fscanf(fp,"%s",str);
		//tem=atoi(str);
		tem=strtol(str,NULL,16);
		temtem=tem-(tem%16);
		if(flag1==1)
		{
			printf("\ntem\t%X\n",tem);
			printf("\ntemtem\t%X\n",temtem);
		}
		//printf("\n%d\n",tem);
		//printf("%d\n",tem);
		//fprintf(fp2,"\n%d\n",tem);
		//printf("\nreaches1\n");
		//printf("%d\n",start1-start);
		/*if(flag1!=0)
			printf("\nreaches\n");*/
		while(((start1-start))<temtem)
		{
			fprintf(fp2,"%X\t",start1);
			for(i=0;i<4;i++)
			{
				fprintf(fp2,"XXXXXXXX\t");
			}
			fprintf(fp2,"\n");
			start1=start1+16;
		}
		/*if(flag1==1)
			printf("\nreaches 1\n");*/
		fprintf(fp2,"%X\t",start1);
		a1:
		noc=noc1=0;
		fgets(str,50,fp);
		if(flag1!=0)
		{
			start=strtol(stad[l++],NULL,16);
			temtem=tem;
		}
		if((temtem+start)>start1)
                {
                                //printf("\nEnters");
                                //printf("%d\n",((temtem+start)-start1));
                                if(((temtem+start)-start1)%2==0)
                                {
                                        //printf("\neven");
                                        k=start1;
                                        while(k<(temtem+start))
                                        {
                                                fprintf(fp2,"XXXXXXXX\t");k=k+4;
						counter++;
                                        }
                                }
                                else
                                {
                                        //printf("\nodd");
                                        k=start1;
                                        while(k<((temtem+start)-1))
                                        {
                                                fprintf(fp2,"XXXXXXXX\t");k=k+4;
						counter++;
                                        }
                                        while(k<temtem+start)
                                        {
                                                fprintf(fp2,"XX");k++;
						noc1=noc1+2;
                                        }
                                }
            	}
		//printf("\n%s\n",str);
		i=1;
		while(!isspace(str[i]))
			i++;
		i++;
		if(flag1==1)
			printf("i\t%c\n",str[i]);
		//printf("\n%d\n",m1);
		//printf("\nreaches2\n");
		while(i<strlen(str))
		{
			flag=0;
			for(j=0;j<m1;j++)
			{
				//tem2=atoi(modi1[j]);
				tem2=strtol(modi1[j],NULL,16);
				//printf("\n%d\n",tem2);
				if((tem==tem2)||(tem+1==tem2))
				{
					//printf("\n%d\n",tem);
					flag=1;
					if(tem!=tem2&&flag1!=0)
					{
						printf("%c",str[i]);
						tbl[tb][tb1++]=str[i++];
						l++;
						noc1++;
						printf("%c",str[i]);
						tbl[tb][tb1++]=str[i++];
						l++;
						noc1++;
						printf("\n");
					}
					k=0;noc=0;
					while(!isspace(str[i]))
					{
						temm[k++]=str[i++];
						noc++;
					}
					//tem=tem+3;
					i++;
					//printf("\n\n%c%c\n\n",str[i],str[i+1]);
					temm[k]='\0';
					stol1=strtol(temm,NULL,16);
					tem3=stol1;
					//printf("%c\n",sign[j]);
					//printf("%X\n",atoi(modi2[j]));
					do
					{
						stol2=strtol(modi2[j],NULL,16);
						if(sign[j]=='+')
							tem3=tem3+stol2;
						else
							tem3=tem3-stol2;
						j++;
					}while(strcmp(modi1[j-1],modi1[j])==0);
					//l=0;
					//temtem=tem3;
					//printf("stolnew\t%X\n",tem3);
					//printf("%Xtemtem\t",temtem);
					/*while(tem3!=0)
					{
						critic[l++]=tem3%10;
						tem3=tem3/10;
					}
					critic[l]='\0';*/
					sprintf(critic,"%X",tem3);
					//printf("critic\t%s\n",critic);
					th=0;
					//tbl[tb][tb1++]='Y';
					while(th<strlen(critic))
					{
						if(noc1>=8)
						{
							//printf("\nend\n");
							tbl[tb][tb1]='\0';
							tb++;
							tb1=0;noc1=0;
						}	
						tbl[tb][tb1++]=critic[th];
						th++;
						noc1++;
					}
					//printf("\nnoc1\t%d\n",noc1);
					if(noc1<8)
					{
						while(noc1!=8&&i<strlen(str))
						{
							if(isspace(str[i]))
							{
								//tem=tem+3;
								i++;
							}
							tbl[tb][tb1++]=str[i++];
							noc1++;
							//if(isspace(str[i]))
							//	tem=tem+3;
						}
						//tem=tem+3;
					}
					//printf("\nnoc1\t%d\n",noc1);						
					if(noc1<8)
					{
						while(noc1!=8)
						{
							tbl[tb][tb1++]='X';
							noc1++;	
						}
					}
					tbl[tb][tb1]='\0';
					//printf("tbl\t%s\n",tbl[tb]);
					tb++;tb1=0;noc1=0;
					break;
				}
			}
			if(flag!=1)
			{
				//printf("\nflag0\n");
				tb1=0;
				//printf("\n%c\n",str[i+1]);
				while(noc1<8&&i<strlen(str))
				{
					noc1++;
					if(isspace(str[i]))
					{
						//tem=tem+3;
						i++;
					}
					tbl[tb][tb1++]=str[i++];
				}
				if(noc1<8)
				{
					//printf("%d\n",noc1);
					//tbl[tb][tb1++]='x';
					while(noc1<=8)
					{
						tbl[tb][tb1++]='X';
						//printf("%c",tbl[tb][tb1-1]);
						noc1++;
					}
				}
				if(noc1==8)
					noc1=0;
				tbl[tb][tb1]='\0';
				//printf("%s\n",tbl[tb]);
				//printf("%d\n",strlen(tbl[tb]));
				//printf("\n");
				tb1=0;tb++;
			}
			tem=tem+4;
			//printf("%d\n",i);
		}
		for(th=0;th<tb;th++)
		{
			if(counter==4)
			{
				fprintf(fp2,"\n");
				start1=start1+16;
				fprintf(fp2,"%X\t",start1);
				counter=0;
			}
			fprintf(fp2,"%s",tbl[th]);
			if((strlen(tbl[th])<8)&&(th!=0))
			{
				k=strlen(tbl[th]);
				while(k<8)
				{
					fprintf(fp2,"X");
					k++;
				}
			}
			fprintf(fp2,"\t");
			counter++;
		}
		/*while(tb<4)
		{
			fprintf(fp2,"XXXXXXXX\t");
			tb++;counter++;
		}*/
		while(counter<4)
		{
			fprintf(fp2,"XXXXXXXX\t");
			counter++;
		}
		fprintf(fp2,"\n");
		tb=0;tb1=0;noc1=0;counter=0;
		fscanf(fp,"%s",str);
		if(strcmp(str,"T")==0)
		{
			fscanf(fp,"%s",str);
			tem=strtol(str,NULL,16);
			temtem=tem-(tem%10);
			start1=start1+16;
			//fprintf(fp2,"%X\t",start1);
			while((start1-start)!=temtem)
			{
				fprintf(fp2,"%X\t",start1);
				for(th=0;th<4;th++)
				{
					fprintf(fp2,"XXXXXXXX\t");
				}
				fprintf(fp2,"\n");
				start1=start1+16;
			}
			temtem=tem;
			fprintf(fp2,"%X\t",start1);
			goto a1;
		}
		else
		{
			//break;
			printf("%d\n",noe);
			while(strcmp(str,"E")!=0)
				fscanf(fp,"%s",str);
			noet++;
			if(noet>=noe)
				break;
			else
			{
				m1=0;
				flag1=1;
				goto b1;
			}
		}
				
	}
	fclose(fp);
	fclose(fp2);
}

main()
{
	//printf("hi");
	cl();
	/*for(i=0;i<tb;i++)
	{
		for(j=0;j<strlen(tbl[i]);j++)
		{
			if(isalpha(tbl[i][j]))
				printf("%c",tbl[i][j]);
			else
				printf("%d",tbl[i][j]);
		}
		printf("\t");
	}*/
}
